# %easypay_count% 订单数量
# %easypay_count_{player}% 指定玩家订单数量
# %easypay_count_{player}_{service}% 指定玩家指定服务订单数量
# %easypay_price_{player}% 指定玩家订单数量金额
# %easypay_price_{player}_{service}% 指定玩家指定服务订单数量金额
# %easypay_top_name_{1-10}% 排行榜用户名
# %easypay_top_price_{1-10}% 排行榜金额
# 注意 为节约性能 以上PAPI变量 有15秒的刷新缓存时间

# 内置 service "wechat-official" 为微信官方 "wechat" 为微信dlc（监听消息的） alipay 为支付宝官方

# FAQ 如何区分正在使用的EvalEx版本
# - 您的服务器运行在Java11及以上的环境上将使用EvalEx3
# - 反之低于Java11则使用EvalEx2
# EvalEx3 函数文档 https://ezylang.github.io/EvalEx/
# EvalEx2 函数文档 https://github.com/ezylang/EvalEx/tree/2.x
# EvalEx2 与 EvalEx3 之间格式并不互通 请查看文档获取格式
# 默认为EvalEx3示例 注释带有EvalEx2示例

# 启用该选项将禁用EvalEx库 [包括2,3]
# 将使用替换方法解析if函数 [expression-evaluator]
# 格式文档 https://github.com/ridencww/expression-evaluator
no-evalex: false

alipay:
  api: 'https://openapi.alipay.com/gateway.do'
  appid: 'appid'
  private-key: 'private-key'
  public-key: 'public-key'
  # 回调url 无特殊需求无需更改
  notify-url: 'https://www.baidu.com/'
  # 店员识别id 随便填
  store-id: 'easy_pay'
wechat-official:
  # 微信appid
  appid: "wx5exxxxxxxxx"
  # 商户号
  mchid: "12453452"
  # 证书序列号
  merchantSerialNumber: 'merchantSerialNumber'
  # 私有证书
  privateKeyPath: 'pem/apiclient_key.pem'
  # 微信支付平台证书
  wechatPayCertificatePath: 'pem/weixing.pem'
wechat:
  # 启用微信DLC功能
  enable: false
  # 微信DLC通信服务器地址
  server: "127.0.0.1:42267"
  # 微信收款二维码内容
  qrcode: ""
  # 是否在订单被锁定时启用价格浮动(增加价格直到能够付款-最小加价单位0.01)
  dynamic-cost: false
  # 订单等待时长 (单位: 秒) 超时取消订单
  wait-time: 60
  # 重连次数 (超过次数无法连接将停止尝试 直到重载插件)
  max-retry: 5
paypal:
  # 启用PayPal功能
  enable: false
  # 环境 (SANDBOX/PRODUCTION)
  # 生产环境上使用请设置为PRODUCTION
  environment: SANDBOX
  # PayPal提供的Client ID
  client-id: "CLIENT_ID"
  # PayPal提供的Client Secret
  client-secret: "CLIENT_SECRET"
  # 收款货币 (CNY/USD/HKD等 更多请查阅PayPal restful api文档)
  currency: "HKD"
stripe:
  # 启用Stripe功能
  enable: false
  # Stripe提供的ApiKey私钥
  api-key: "PRIVATE_API_KEY"
  # 收款货币 (CNY/USD/HKD等 更多请查阅Stripe开发文档)
  # https://docs.stripe.com/currencies?presentment-currency=MX#presentment-currencies
  currency: "HKD"
  # 支付成功跳转地址
  success-url: "https://www.baidu.com/"
map:
  # 地图放置位置 MAIN 为主手 OFF 为副手
  hand: 'MAIN'
  # 是否在地图丢弃时取消订单
  cancel-on-drop: false
  # 发包地图模式 (此功能为测试版 仅兼容最新的Minecraft版本 请勿随意开启)
  virtual: false
book:
  # 书本页面 MiniMessage格式
  # https://docs.advntr.dev/minimessage/format.html
  lines:
    - "<click:open_url:${url}><blue><bold> 请点击链接前往支付页面</bold></blue></click>"
    - "<click:open_url:${url}>                            </click>"
    - "<click:open_url:${url}>                            </click>"
    - "<click:open_url:${url}>                            </click>"
    - "<click:open_url:${url}>                            </click>"
    - "<click:open_url:${url}>                            </click>"
    - "<click:open_url:${url}>                            </click>"
    - "<click:open_url:${url}><hover:show_text:'<white>点击此处跳转网页'><red><bold>  !!!点击此处跳转网页!!!</bold></red></hover></click>"
    - "<click:open_url:${url}>                            </click>"
    - "<click:open_url:${url}>                            </click>"
    - "<click:open_url:${url}>                            </click>"
    - "<click:open_url:${url}>                            </click>"
    - "<click:open_url:${url}>                            </click>"
    - "<click:open_url:${url}><blue><bold> 请点击链接前往支付页面</bold></blue></click>"
database:
  mysql:
    # 是否启用mysql 不启用使用sqlite
    enable: false
    host: 'localhost'
    port: 3306
    database: 'minecraft'
    user: 'minecraft'
    passwd: 'minecraft'
# 内置商品
builtin:
  # 自定义金额充值
  CustomPriceItem:
    # 最小金额
    min: 1
    # 最大金额
    max: 100
    # 数量与RMB的比例 1元 = 100
    ratio: 100
    # 商品名称
    name: '自定义金额充值'
    # 订单创建后发送给玩家的消息
    # 使用Java11以下的用户 请使用EvalEx2格式
    # 'if(STREQ("$service","wechat")) title(&a请使用微信扫码支付 &f$price 元, &e填写金额务必与上方一致, 10, 40, 10) return()'
    # 'if(STREQ("$service","alipay")) title(&a请支付 &f$price 元, &7使用支付宝扫码付款, 10, 40, 10) return()'
    actions:
      - 'if("$service" == "wechat") title(&a请使用微信扫码支付 &f$price 元, &e填写金额务必与上方一致, 10, 40, 10) return()'
      - 'if("$service" == "alipay") title(&a请支付 &f$price 元, &7使用支付宝扫码付款, 10, 40, 10) return()'
    # 订单创建前执行
    pre-actions:
      # 下面注释的意思是如果玩家没有 example.permission 权限将不能创建这个订单
      #- 'perm(example.permission) cancel()'
      - 'return()'
    # 订单完成后执行 (解析式)
    rewards:
      - 'if(%easypay_price_$player% == 0) msg(&a您是第一次充值)'
    # 执行的命令
    commands:
      - 'say %player_name% 您充值了 %custom_amount% 点券'
      # 给予点券命令 已注释
      #- 'points give %player_name% %custom_amount%'
items:
  测试命令商品:
    type: 'CommandItem'
    # 价格
    price: 0.01
    # 订单创建后发送给玩家的消息
    # 使用Java11以下的用户 请使用EvalEx2格式
    # 'if(STREQ("$service","wechat")) title(&a请使用微信扫码支付 &f$price 元, &e填写金额务必与上方一致, 10, 40, 10) return()'
    # 'if(STREQ("$service","alipay")) title(&a请支付 &f$price 元, &7使用支付宝扫码付款, 10, 40, 10) return()'
    actions:
      - 'if("$service" == "wechat") title(&a请使用微信扫码支付 &f$price 元, &e填写金额务必与上方一致, 10, 40, 10) return()'
      - 'if("$service" == "alipay") title(&a请支付 &f$price 元, &7使用支付宝扫码付款, 10, 40, 10) return()'
    # 订单创建前执行
    pre-actions:
      # 下面注释的意思是如果玩家没有 example.permission 权限将不能创建这个订单
      #- 'perm(example.permission) cancel()'
      - 'return()'
    # 订单完成后执行 (解析式)
    rewards:
      - 'if(%easypay_price_$player% == 0) msg(&a您是第一次充值)'
    commands:
      - 'say %player_name% 您购买成功了 %item_name%'