# %easypay_count% 订单数量
# %easypay_count_{player}% 指定玩家订单数量
# %easypay_count_{player}_{service}% 指定玩家指定服务订单数量
# %easypay_price_{player}% 指定玩家订单数量金额
# %easypay_price_{player}_{service}% 指定玩家指定服务订单数量金额
# %easypay_top_name_{1-10}% 排行榜用户名
# %easypay_top_price_{1-10}% 排行榜金额
# 注意 为节约性能 以上PAPI变量 有15秒的刷新缓存时间

# 内置 service "wechat-official" 为微信官方 "wechat" 为微信dlc（监听消息的） alipay 为支付宝官方

alipay:
  api: 'https://openapi.alipay.com/gateway.do'
  appid: 'appid'
  private-key: 'private-key'
  public-key: 'public-key'
  # 回调url 无特殊需求无需更改
  notify-url: 'https://www.baidu.com/'
  # 店员识别id 随便填
  store-id: 'easy_pay'
wechat-official:
  # 微信appid
  appid: "wx5exxxxxxxxx"
  # 商户号
  mchid: "12453452"
  # 证书序列号
  merchantSerialNumber: 'merchantSerialNumber'
  # 私有证书
  privateKeyPath: 'pem/apiclient_key.pem'
  # 微信支付平台证书
  wechatPayCertificatePath: 'pem/weixing.pem'
wechat:
  # 启用微信DLC功能
  enable: false
  # 微信DLC通信服务器地址
  server: "127.0.0.1:42267"
  # 微信收款二维码内容
  qrcode: ""
  # 是否在订单被锁定时启用价格浮动(增加价格直到能够付款-最小加价单位0.01)
  dynamic-cost: false
  # 订单等待时长 (单位: 秒) 超时取消订单
  wait-time: 60
map:
  # 地图放置位置 MAIN 为主手 OFF 为副手
  hand: 'MAIN'
  # 是否在地图丢弃时取消订单
  cancel-on-drop: false
database:
  mysql:
    # 是否启用mysql 不启用使用sqlite
    enable: false
    host: 'localhost'
    port: 3306
    database: 'minecraft'
    user: 'minecraft'
    passwd: 'minecraft'
# 内置商品
builtin:
  # 自定义金额充值
  CustomPriceItem:
    # 最小金额
    min: 1
    # 最大金额
    max: 100
    # 数量与RMB的比例 1元 = 100
    ratio: 100
    # 商品名称
    name: '自定义金额充值'
    # 执行的命令
    commands:
      - 'say %player_name% 您充值了 %custom_amount% 点券'
      # 给予点券命令 已注释
      #- 'points give %player_name% %custom_amount%'
items:
  测试命令商品:
    type: 'CommandItem'
    # 价格
    price: 0.01
    commands:
      - 'say %player_name% 您购买成功了 %item_name%'