# %easypay_count% 订单数量
# %easypay_count_{player}% 指定玩家订单数量
# %easypay_count_{player}_{service}% 指定玩家指定服务订单数量
# %easypay_price_{player}% 指定玩家订单数量金额
# %easypay_price_{player}_{service}% 指定玩家指定服务订单数量金额
# %easypay_top_name_{1-10}% 排行榜用户名
# %easypay_top_price_{1-10}% 排行榜金额
# 注意 为节约性能 以上PAPI变量 有15秒的刷新缓存时间
alipay:
  api: 'https://openapi.alipay.com/gateway.do'
  appid: 'appid'
  private-key: 'private-key'
  public-key: 'public-key'
  # 回调url 无特殊需求无需更改
  notify-url: 'https://www.baidu.com/'
  # 店员识别id 随便填
  store-id: 'easy_pay'
wechat:
  # 启用微信DLC功能
  enable: false
  # 微信DLC通信服务器地址
  server: "127.0.0.1:42267"
  # 微信收款二维码内容
  qrcode: ""
  # 是否在订单被锁定时启用价格浮动(增加价格直到能够付款-最小加价单位0.01)
  dynamic-cost: false
  # 订单等待时长 (单位: 秒) 超时取消订单
  wait-time: 60
database:
  mysql:
    # 是否启用mysql 不启用使用sqlite
    enable: false
    host: 'localhost'
    port: 3306
    database: 'minecraft'
    user: 'minecraft'
    passwd: 'minecraft'
items:
  测试命令商品:
    type: 'CommandItem'
    # 价格
    price: 0.01
    # 订单创建后发送给玩家的消息
    actions:
      - 'if("$service" == "wechat") title(&a请使用微信扫码支付 &f$price 元, &e填写金额务必与上方一致, 10, 40, 10) return()'
      - 'if("$service" == "alipay") title(&a请支付 &f$price 元, &7使用支付宝扫码付款, 10, 40, 10) return()'
    # 购买成功后执行命令
    commands:
      - 'say %player_name% 您购买成功了 %item_name%'