name: ${name}
main: ${main}
version: '${version}'
author: xbaimiao
api-version: 1.13
folia-supported: true
softdepend:
  - PlaceholderAPI
  - Vault
  - PlayerPoints
  - CMI
  - XConomy
  - ProtocolLib
update-info: '添加依赖缓存 优化加载时间'
relocate:
  - "kotlin!com.xbaimiao.easypay.shadow.kotlin"
  - "kotlinx!com.xbaimiao.easypay.shadow.kotlinx"
  - "com.google.gson!com.xbaimiao.easypay.shadow.gson"
