name: ${name}
main: ${main}
version: '${version}'
author: xbaimiao
api-version: 1.13
folia-supported: true
softdepend:
  - PlaceholderAPI
  - Vault
  - PlayerPoints
  - CMI
  - XConomy
  - ProtocolLib
  - PacketEvents
update-info: '尝试修复MapId在1.21无法正常获取的问题 PacketEvents要求2.4.0+'
kotlin-version: "1.9.20"
relocate:
  - "kotlin!com.xbaimiao.easypay.shadow.kotlin"
  - "kotlinx!com.xbaimiao.easypay.shadow.kotlinx"
  - "com.google.gson!com.xbaimiao.easypay.shadow.gson"
  - "com.cryptomorin.xseries!com.xbaimiao.easypay.shadow.xseries"
depend-list:
  - "com.github.cryptomorin:XSeries:9.10.0"
