name: ${name}
main: ${main}
version: '${version}'
author: xbaimiao
api-version: 1.13
folia-supported: true
softdepend:
  - PlaceholderAPI
  - Vault
  - PlayerPoints
  - CMI
  - XConomy
  - ProtocolLib
update-info: '支持1.20.6'
kotlin-version: "1.9.20"
relocate:
  - "kotlin!com.xbaimiao.easypay.shadow.kotlin"
  - "kotlinx!com.xbaimiao.easypay.shadow.kotlinx"
  - "com.google.gson!com.xbaimiao.easypay.shadow.gson"
  - "com.cryptomorin.xseries!com.xbaimiao.easypay.shadow.xseries"
depend-list:
  - "com.github.cryptomorin:XSeries:9.10.0"
