name: ${name}
main: ${main}
version: '${version}'
author: xbaimiao
api-version: 1.13
folia-supported: true
softdepend:
  - PlaceholderAPI
  - Vault
  - PlayerPoints
  - CMI
  - XConomy
  - ProtocolLib
update-info: 'PlaceholderAPI 变量 不再使用_分割 而是使用:分割'
